In [1]:
import numpy as np

from   scipy import stats

In [81]:
np.random.seed(0)

X    = np.random.normal(size = (10, 3))

Q, R = np.linalg.qr(X)

U, s, Vt = np.linalg.svd(R)

s[0] = 0

X = Q @ U @ np.diag(s) @ Vt

w = np.array([-10, 0, 1])

y = X @ w

In [27]:
X.T @ X @ np.linalg.lstsq(X, y, rcond = -1)[0] - X.T @ y

array([ 8.88178420e-16, -1.77635684e-15,  1.77635684e-15])

In [28]:
X.T @ X @ np.linalg.solve(X.T @ X, X.T @ y) - X.T @ y

array([0., 0., 0.])

In [29]:
U, s, Vt = np.linalg.svd(X, False)

X.T @ X @ Vt.T @ np.diag(1 / s) @ U.T @ y - X.T @ y

array([-6.66133815e-16,  1.77635684e-15, -1.77635684e-15])

In [30]:
X.T @ X @ w - X.T @ y

array([2.22044605e-16, 0.00000000e+00, 0.00000000e+00])

In [31]:
from lib.linear import LinearRegressionConjugateGradientDescent, LinearRegressionSteepestDescent

model = LinearRegressionSteepestDescent(fit_intercept = False).fit(X, y)
X.T @ X @ model.w - X.T @ y

array([-1.19859233e-06,  2.64664431e-06, -1.39859876e-06])

In [38]:
np.save('X.npy', X)

In [40]:
X.mean(axis = 0)

array([0.0026925 , 0.00082115, 0.04503154])

In [41]:
np.cov(X, rowvar = False)

array([[ 0.17264296, -0.41743016, -0.02273044],
       [-0.41743016,  1.04813471,  0.29539606],
       [-0.02273044,  0.29539606,  1.49146945]])

In [82]:
X.T @ X @ w

array([-0.42065696, -8.9063191 ,  2.34221251])

In [63]:
np.linalg.solve(X.T @ X, X.T @ y)

array([0.27172373, 0.53063361, 0.91428571])

In [85]:
np.linalg.lstsq(Vt.T @ X.T @ X, Vt.T @ X.T @ y, rcond = -1)[0]

array([-1.45849566,  3.56398889,  0.42430189])

In [67]:
s[s < 1e-5] = 0

Vt.T @ np.

array([3.88034651e+00, 3.06161602e+00, 2.93343099e-16])